### ISSUE TITLE
Bootstrap left bar links bug

### ISSUE THREAD

**Issue by rafaelstz** [comandosgit/comandosgit.github.io#2]

**Comment by pixelasticity** [comment]
To fix this bug, you could either move the id attributes to the h4 elements or you have to reformat your code.

Right now it's like this:
`<div class="row">
    <div id="name">
        <h4 class="col-xs-12">`

It should be more like this:
`<div class="row">
    <div class="col-xs-12">
        <h4 id="name">`

All column classes are floated left so the containers collapse. I can fix in a pull request if you want to assign it to me.

**Comment by rafaelstz** [comment]
Yes sure, fell free to send a pull request, thanks :smile:

**Comment by pixelasticity** [comment]
👍

**Comment by tanvibhakta** [comment]
is @pixelasticity working on this?

**Comment by aksh1** [comment]
#21 well there is just linking error so, I fixed it  @rafaelstz

**Comment by rafaelstz** [comment]
Thanks 😄
