### ISSUE TITLE
Developer link and license on footer

### ISSUE THREAD

**Issue by rafaelstz** [comandosgit/comandosgit.github.io#4]

**Comment by akash-vartak** [comment]
So is this still open or closed? Because I can see a developer link but no license link...http://comandosgit.github.io/

**Comment by rafaelstz** [comment]
@akash-vartak  do you want to put the license in the footer? feel free, it would be very good!

**Comment by danielswiatek** [comment]
Can you tell me what´s the Developer License is?

**Comment by rafaelstz** [comment]
@danielswiatek sure, MIT

**Comment by dance2die** [comment]
Working on it.

**Comment by KayDee** [comment]
Its already done. You can close the issue.

**Comment by rafaelstz** [comment]
Thanks @KayDee
